[game]
MAX_LOGIC_FRAMES = 30
MAX_RENDER_FRAMES = 60
MAX_GRAVITY_LEVEL = 13 #1G
NO_GRAVITY = false

[ai]
PPS = 1
MAX_AI_MOVEMENTS_PER_SECOND = 5
MAX_NEXT_BLOCK = 6
# HEIGHT_WEIGHT = 109
# BUMPINESS_WEIGHT = 8
# HOLES_WEIGHT = 706
# SCORE_WEIGHT = 423
# EMPRY_LINES_WEIGHT = 924
# BACK_TO_BACK_WEIGHT = 1
# COMBO_WEIGHT = 1
# heightWeight:79,bumpinessWeight:83,holesWeight:408,scoreWeight:823,
# emptyLinesWeight:593,backToBackWeight:591,comboWeight:365,tetrisWeight:718,
# perfectClearWeight:386,tSpinWeight:465,singleWeight:303,doubleWeight:545,
# tripleWeight:679
[score]

[tuner]
MAX_GAMES = 10
MAX_MOVES = 300
MAX_THREAD = 8
MAX_GENERATIONS = 100
MAX_POPULATIONS = 100
# DATA_DIR = "../logs/data.toml"

