[game]
MAX_LOGIC_FRAMES = 60
MAX_RENDER_FRAMES = 60
MAX_GRAVITY_LEVEL = 13

[ai]
MAX_AI_MOVEMENTS_PER_SECOND = 100
MAX_NEXT_BLOCK = 10
HEIGHT_WEIGHT = 0.410664
BUMPINESS_WEIGHT = 0.0252176
HOLES_WEIGHT = 0.430837
SCORE_WEIGHT = 0.183875
EMPRY_LINES_WEIGHT = 0.781849

[score]

[tuner]
POPULATION = 100
MAX_GAMES = 10
MAX_MOVEMENTS = 400
