[game]
MAX_LOGIC_FRAMES = 60
MAX_RENDER_FRAMES = 60
MAX_GRAVITY_LEVEL = 13 #1G

[ai]
MAX_AI_MOVEMENTS_PER_SECOND = 10
MAX_NEXT_BLOCK = 10
HEIGHT_WEIGHT = 109
BUMPINESS_WEIGHT = 8
HOLES_WEIGHT = 706
SCORE_WEIGHT = 423
EMPRY_LINES_WEIGHT = 924
BACK_TO_BACK_WEIGHT = 1
COMBO_WEIGHT = 1

[score]

[tuner]
POPULATION = 100
MAX_GAMES = 10
MAX_MOVEMENTS = 400
