[game]
MAX_LOGIC_FRAMES = 60
MAX_RENDER_FRAMES = 60
MAX_GRAVITY_LEVEL = 13

[ai]
MAX_AI_MOVEMENTS_PER_SECOND = 100
MAX_NEXT_BLOCK = 10
HEIGHT_WEIGHT = 0.354349
BUMPINESS_WEIGHT = 0.00589607
HOLES_WEIGHT = 0.786525
SCORE_WEIGHT = 0.483883
EMPRY_LINES_WEIGHT = 0.147098

[score]

[tuner]
POPULATION = 100
MAX_GAMES = 10
MAX_MOVEMENTS = 400
#  
# 41.13 16450-400 5
# 52.68 15805-300 10
#       16875-300 10
#       23820-300 10